Add CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -42,6 +42,7 @@ jobs:
       - name: Clean previous allure results
         run: |
           rm -rf allure-results allure-report
+          rm -rf target/allure-results target/allure-report
 
       # Шаг 6: Запуск тестов
       - name: Run Java UI tests
@@ -49,7 +50,7 @@ jobs:
 
       # Шаг 7: Просмотр содержимого allure-results (для отладки)
       - name: Debug:list contents of allure-results
-        run: ls -R allure-results || echo "No results found"
+        run: ls -R target/allure-results || echo "No results found"
 
       # Шаг 8: Установка Allure CLI
       - name: Install Allure CLI
@@ -63,18 +64,48 @@ jobs:
       # Шаг 9: Генерация отчета Allure
       - name: Generate Allure report
         run: |
-          allure generate allure-results --clean -o allure-report
+          allure generate target/allure-results --clean -o target/allure-report
 
       # Шаг 10: Загрузка отчета Allure как артефакт
       - name: Upload Allure report
         uses: actions/upload-artifact@v4
         with:
           name: allure-report
-          path: allure-report
+          path: target/allure-report
 
       # Шаг 11: Загрузка результатов Allure как артефакт
       - name: Upload Allure results
         uses: actions/upload-artifact@v4
         with:
           name: allure-results
-          path: allure-results
+          path: target/allure-results
+
+      # Шаг 12: Логи при падении тестов
+      - name: Upload Test Logs if failed
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-logs
+          path: logs/test_logs
+
+      # Шаг 13: Логи CI при падении
+      - name: Upload CI Logs if failed
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: ci-logs
+          path: logs/ci_logs
+
+      # Шаг 14: Установка Newman
+      - name: Install Newman
+        run: npm install -g newman
+
+      # Шаг 15: Run Postman collections (recursive, clean output)
+      - name: Run Postman collections
+        run: |
+          echo "Searching for *_Collection.postman_collection.json files in ./src/postman/collections/..."
+
+          find ./src/postman/collections -type f -name "*_Collection.postman_collection.json" | while read collection; do
+            echo "Running: $(basename "$collection")"
+            newman run "$collection" || echo "Collection failed or is empty: $(basename "$collection")"
+          done
